# Generated by Django 3.0.5 on 2020-05-03 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_auto_20200503_1202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=10)),
                ('nick', models.CharField(max_length=10)),
                ('hosted_rooms', models.ManyToManyField(related_name='hosted', to='game.Game')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
