# Generated by Django 3.0.6 on 2020-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='properties',
            field=models.CharField(default='', max_length=400, null=True),
        ),
    ]
