# Generated by Django 3.0.5 on 2020-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200503_1202'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hosted_rooms',
            field=models.ManyToManyField(blank=True, null=True, related_name='hosted', to='game.Game'),
        ),
    ]
