# Generated by Django 3.0.6 on 2020-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='tossed_dice',
            field=models.BooleanField(default=False),
        ),
    ]
