# Generated by Django 3.0.6 on 2020-12-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_player_moved'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='moved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
