# Generated by Django 3.0.5 on 2020-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200503_1202'),
        ('player', '0002_auto_20200503_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='decription',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hosted_rooms',
            field=models.ManyToManyField(blank=True, related_name='hosted', to='game.Game'),
        ),
    ]
