# Generated by Django 3.0.6 on 2020-12-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_player_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
    ]
