# Generated by Django 3.0.5 on 2020-05-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20200503_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='decription',
            new_name='description',
        ),
    ]
