# Generated by Django 3.0.6 on 2020-12-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='moved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
