# Generated by Django 3.0.5 on 2020-05-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_who_is_ready'),
        ('player', '0005_remove_player_hosted_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
