# Generated by Django 3.0.6 on 2020-05-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_in_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='in_room',
        ),
    ]
