# Generated by Django 3.0.6 on 2020-12-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nr_of_fields', models.IntegerField(default=28)),
                ('special', models.IntegerField(default=8)),
                ('start_money', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('host', models.CharField(max_length=10)),
                ('is_played', models.BooleanField(default=False)),
                ('max_players', models.IntegerField(default=4)),
                ('turn', models.IntegerField(default=1)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_config', to='game.Config')),
                ('turn_of_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='czyja_tura', to='player.Player')),
                ('who_is_playing', models.ManyToManyField(blank=True, related_name='guys_playing', to='player.Player')),
                ('who_is_ready', models.ManyToManyField(blank=True, related_name='guys_ready', to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=100)),
                ('grade', models.IntegerField(default=1)),
                ('typeof', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeOfField', to='game.FieldType')),
            ],
        ),
    ]
