# Generated by Django 3.0.5 on 2020-05-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.CharField(max_length=10),
        ),
    ]
