# Generated by Django 3.0.5 on 2020-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='players_ready',
            field=models.IntegerField(default=0),
        ),
    ]
