# Generated by Django 3.0.6 on 2020-10-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='type',
        ),
    ]
