# Generated by Django 3.0.6 on 2020-12-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='first_level_cost',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='config',
            name='money_for_round',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='config',
            name='upgrade_cost',
            field=models.IntegerField(default=500),
        ),
    ]
