# Generated by Django 3.0.6 on 2020-11-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20201013_1309'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamefields', to='game.Game'),
        ),
        migrations.AddField(
            model_name='field',
            name='nr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='typeof',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeOfField', to='game.FieldType'),
        ),
        migrations.AlterField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldOwner', to='player.Player'),
        ),
    ]
