# Generated by Django 3.0.5 on 2020-05-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200502_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='want_to_play',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
