# Generated by Django 3.0.6 on 2020-12-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='positions',
        ),
    ]
