# Generated by Django 3.0.6 on 2020-10-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('game', '0002_field_typeof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieldOwner', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='field',
            name='typeof',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeOfField', to='game.FieldType'),
        ),
    ]
