# Generated by Django 3.0.6 on 2020-11-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201119_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nr_of_fields', models.IntegerField(default=28)),
                ('special', models.IntegerField(default=8)),
                ('start_money', models.IntegerField(default=1000)),
            ],
        ),
    ]
