# Generated by Django 3.0.5 on 2020-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_remove_player_hosted_rooms'),
        ('game', '0003_auto_20200503_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='who_is_ready',
            field=models.ManyToManyField(to='player.Player'),
        ),
    ]
