# Generated by Django 3.0.6 on 2020-11-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_config', to='game.Config'),
        ),
    ]
