# Generated by Django 3.0.6 on 2020-10-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201013_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='nr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
