# Generated by Django 3.0.5 on 2020-05-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_who_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='who_is_ready',
        ),
    ]
