# Generated by Django 3.0.5 on 2020-05-01 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_auto_20200501_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='want_to_play',
            field=models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
