# Generated by Django 3.0.6 on 2020-05-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_remove_player_in_room'),
        ('game', '0005_remove_game_who_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='who_is_ready',
            field=models.ManyToManyField(related_name='guys_ready', to='player.Player'),
        ),
    ]
