# Generated by Django 3.0.6 on 2020-05-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_remove_player_in_room'),
        ('game', '0006_game_who_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='who_is_ready',
            field=models.ManyToManyField(blank=True, related_name='guys_ready', to='player.Player'),
        ),
    ]
