# Generated by Django 3.0.6 on 2020-05-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_remove_player_in_room'),
        ('game', '0007_auto_20200510_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pierwszy', to='player.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='forth_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='czwarty', to='player.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='second_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugi', to='player.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='third_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trzeci', to='player.Player'),
        ),
    ]
