# Generated by Django 3.0.5 on 2020-05-01 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200501_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nick',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=10),
        ),
    ]
