# Generated by Django 3.0.6 on 2020-05-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_remove_player_in_room'),
        ('game', '0009_auto_20200512_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pierwszy', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='second_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugi', to='player.Player'),
        ),
    ]
