# Generated by Django 3.0.6 on 2020-05-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200512_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='forth_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='third_player',
        ),
    ]
