# Generated by Django 3.0.6 on 2020-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_player_in_game'),
        ('game', '0013_auto_20200513_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='who_is_playing',
            field=models.ManyToManyField(blank=True, related_name='guys_playing', to='player.Player'),
        ),
    ]
