# Generated by Django 3.0.6 on 2020-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_who_is_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_of_player',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
