# Generated by Django 3.0.6 on 2020-05-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_player_in_game'),
        ('game', '0015_auto_20200513_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn_of_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='czyja_tura', to='player.Player'),
        ),
    ]
