# Generated by Django 3.0.6 on 2020-05-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20200513_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn_of_player',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
