# Generated by Django 3.0.6 on 2020-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20200513_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='how_many_players',
            field=models.IntegerField(default=3),
        ),
    ]
