# Generated by Django 3.0.6 on 2020-05-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_player_in_game'),
        ('game', '0019_game_how_many_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nastepny', to='player.Player'),
        ),
    ]
