# Generated by Django 3.0.6 on 2020-05-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_game_next_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='first_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='how_many_players',
        ),
    ]
