# Generated by Django 3.0.6 on 2020-05-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20200515_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players_ready',
        ),
    ]
