# Generated by Django 3.0.6 on 2020-05-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_remove_game_players_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='forth_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='next_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='second_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='third_player',
        ),
    ]
