# Generated by Django 3.0.6 on 2020-05-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0008_player_in_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Turn', models.IntegerField(default=1)),
                ('how_many_players_play', models.IntegerField(default=2)),
                ('is_played', models.BooleanField(default=False)),
                ('first_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pierwszy', to='player.Player')),
                ('forth_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='czwarty', to='player.Player')),
                ('second_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugi', to='player.Player')),
                ('third_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trzeci', to='player.Player')),
            ],
        ),
    ]
