# Generated by Django 3.0.6 on 2020-05-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_player_in_game'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='who_is_playing',
            field=models.ManyToManyField(blank=True, related_name='players_playing', to='player.Player'),
        ),
    ]
